import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Session } from "next-auth";
import { Header } from "./components/Header";

export const metadata: Metadata = {
  title: "TicketShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session
}: Readonly<{
  children: React.ReactNode;
  session: Session;
}>) {
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body>
          <Header />
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}
