import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Header } from "./components/Header";
import { auth } from "@/auth";

export const metadata: Metadata = {
  title: "TicketShop",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {

  const session = await auth();

  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body>
          <Header />
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}
