import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Header } from "./components/Header";
import { auth } from "@/auth";
import { Footer } from "./components/Footer";

export const metadata: Metadata = {
  title: "TicketShop",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {

  const session = await auth();

  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body className="flex flex-col min-h-screen">
          <Header />
          <main className="flex-grow">
            {children}
          </main>
          <Footer />
        </body>
      </SessionProvider>
    </html>
  );
}
